#!/usr/bin/env python3

import matplotlib.pyplot as plt
import numpy as np
import time
import sys
import os

times = []
iterations = [1, 10, 100, 1000]

for i in sys.argv[1:]:
    times.append([0, 0, 0, 0])

for command in range(len(sys.argv[1:])):
    for it in range(len(iterations)):
        print("Starting " + str(iterations[it]) + "\tfor command `" + str(sys.argv[command + 1]) + "`")
        start = time.time()
        for i in range(iterations[it]):
            os.system(sys.argv[command + 1] + " > /dev/null")
        times[command][it] = (time.time() - start)

for i in range(len(sys.argv[1:])):
    plt.plot(iterations, times[i], "o-", label=sys.argv[i + 1])
    for i_x, i_y in zip(iterations, times[i]):
        plt.text(i_x, i_y, '{:.4f}'.format(i_y))

plt.legend(loc = "best")
plt.ylabel("Time")
plt.xlabel("Iterations")
plt.xscale("log")
plt.yscale("log")
plt.show()
